repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.4.1
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
        args: ["--fix", "--select=E,F,W,T"]
        stages: [pre-commit]
        types: [python]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        args: ["--print-width=120"]
        stages: [pre-commit]
        files: ".*.md"
  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.1-beta
    hooks:
      - id: hadolint
        types: [file]
        files: "Dockerfile.*"
        args: ["--ignore=DL3033","--ignore=DL3041","--ignore=DL3059", "--ignore=DL3008", "--ignore=DL3013", "--ignore=DL3004"]
