site_name: Satellite Images Exploration
site_description: Explore and analyze satellite images with deep learning techniques.
site_author: Tristan Giandoriggio

theme:
  name: material

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

plugins:
  - search
